### ISSUE TITLE
IPFS limit on MerkleDAG node size transfer (4MB).

### ISSUE THREAD

**Issue by diasdavid** [diasdavid/registry-mirror#19]
@whyrusleeping, any ideas on how to overcome the MerkleDAG node size limit so that we can transfer the full npm list?

**Comment by whyrusleeping** [comment]
![image](https://cloud.githubusercontent.com/assets/1243164/11805422/4ab42226-a2c0-11e5-8f21-dcce44187f68.png)

**Comment by diasdavid** [comment]
eheheh :D I heard we need some @jbenet approval!

**Comment by diasdavid** [comment]
A hack suggested by @whyrusleeping while we don't have directory sharding

```
'ipfs block get <npm root> | ipfs add'
then on the other side: 'ipfs cat <that hash> | ipfs block put'
```

**Comment by jbenet** [comment]
> A hack suggested by @whyrusleeping while we don't have directory sharding

hhahaha <3 that.  Yay unix
