### ISSUE TITLE
Make it easy to see which modules have already been "cloned"

### ISSUE THREAD

**Issue by diasdavid** [diasdavid/registry-mirror#8]
A fast `ipfs files ls /npm-registry` would take care of this enhancement

@whyrusleeping, you had some ideas? :)

**Comment by Dignifiedquire** [comment]
This would be really good!

**Comment by diasdavid** [comment]
Once this is merged, we can make it a feature of the CLI! :) https://github.com/ipfs/go-ipfs/pull/2007

**Comment by Dignifiedquire** [comment]
@diasdavid the referenced issue has been merged what else do you want to do here, add a `search` command? or just a `registry-mirror ls` ?

**Comment by diasdavid** [comment]
oh good idea! having search would be very helpful to identify if something is there already

**Comment by diasdavid** [comment]
on https://github.com/diasdavid/registry-mirror/pull/15
